# Generated by Django 2.2.16 on 2022-09-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, help_text='Введите ссылку', null=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
